--- 
language: en
pipeline: 
  - 
    model: en_core_web_md
    name: SpacyNLP
  -
    name: SpacyTokenizer
  - 
    case_sensitive: false
    name: RegexFeaturizer
  - 
    name: CountVectorsFeaturizer
  - 
    name: CRFEntityExtractor
    use_lookup_tables: true
    use_regexes: true
  - 
    name: LexicalSyntacticFeaturizer
  - 
    name: CountVectorsFeaturizer
  - 
    analyzer: char_wb
    max_ngram: 4
    min_ngram: 1
    name: CountVectorsFeaturizer
  - 
    entity_recognition: true
    epochs: 100
    name: DIETClassifier
  - 
    name: EntitySynonymMapper

  - 
    name: EntitySynonymMapper
policies: 
  - 
    name: MemoizationPolicy
  - 
    epochs: 100
    max_history: 5
    name: TEDPolicy
  - 
    name: MappingPolicy
